<a href="https://colab.research.google.com/github/b-hill/cop4630/blob/master/hw4_p1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Imports + Seed

In [0]:
import numpy as np
np.random.seed(0)

### Exceptions 

In [0]:
class MatrixTypeError(Exception):
  def __init__(self, error):
    self.error = error

class ShapeError(Exception):
  def __init__(self, error):
    self.error = error

class SizeError(Exception):
  def __init__(self, error):
    self.error = error

### 2D Convolution 

In [0]:
# perform 2d convolution, all matrices are square with even or odd size
# does NOT pad edges of input with zeros so output is usually smaller than input
def conv2d(input_mat, kernal_mat):

  # check arg types
  if type(input_mat) is not np.ndarray:
    raise MatrixTypeError ('arg input_mat is not an ndarray')
  if type(kernal_mat) is not np.ndarray:
    raise MatrixTypeError ('arg kernal_mat is not an ndarray')

  # get arg shapes
  s_k = kernal_mat.shape[0]
  s_i = input_mat.shape[0]

  # check dim
  if len(input_mat.shape) != 2:
    raise ShapeError ('arg input_mat is not 2D')
  if len(kernal_mat.shape) != 2:
    raise ShapeError ('arg kernal_mat is not 2D')

  # check if square
  if input_mat.shape[0] != input_mat.shape[1]:
    raise ShapeError ('arg input_mat is not square')
  if kernal_mat.shape[0] != kernal_mat.shape[1]:
    raise ShapeError ('arg kernal_mat is not square')

  # check if sizes are compatible 
  if s_k > s_i:
    raise SizeError('arg kernal_mat is of greater size than arg input_mat')

  # calc out shape
  s_o = s_i - s_k + 1

  # init out matrix
  output_mat = np.zeros((s_o, s_o))

  # flip
  # without this operation its just a correaltion, not a convolution
  kernal_mat = np.flip(kernal_mat)

  # convolve 
  for i in range(s_o):
    for j in range(s_o):
      output_mat[i][j] = np.sum(input_mat[i:i+s_k, j:j+s_k] * kernal_mat)

  return output_mat

## Implementation

### Arg generation

In [0]:
input_mat = np.random.randint(-3, 3, size=(7,7))
kernal_mat = np.random.randint(-3, 3, size=(3,3))

### Testing

In [32]:
conv = conv2d(input_mat, kernal_mat)
print(conv)

[[-15. -23. -16.  -8.  -9.]
 [-11. -17.  -3.   7.   6.]
 [-12. -15.   1.   9.   6.]
 [-15. -23. -11.   6.   3.]
 [ -9. -17. -12.   1.  -2.]]
